name: app-b
on:
  push:
    # run this workflow when files inside app-b change
    # or this workflow changes
    # or the root package.json changes
    paths:
      - 'apps/app-b/**'
      - package.json
      - .github/workflows/app-b.yml
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v2
        with:
          working-directory: apps/app-b
          start: npm start
